### ISSUE TITLE
Usability for newbies

### ISSUE THREAD

**Issue by goulu** [tablord/tablord#9]
some suggestions to make it easier to start for newbies like me:

1. make richText default instead of code, so that user can start typing immediately.  It should be as easy as typing in a new Word document.
2. assign intuitive keys shortcuts to the input-group of buttons, like Ctrl-Enter for append (and assign the same input-group type as the original block.
3. ideally (replaces 1 and 2) make the type of the block automatic (but overridable) : if it can be interpreted as code, the it is code (looks like #6 ), otherwise it is rich text. Sections, page breaks should be special rich text (Markdown ?)
4. start the documentation with a "getting started" section, 
5. or include it as a default "new sheet" for newbies (option in the profile ?)

**Comment by goulu** [comment]
just (re) discovered code could be entered in {{}} :-)

**Comment by marcnicole** [comment]
partially addressed since v1.0.1 (in production) 
for point 1 and 2
3 is a good idea, but kept for the future (==> new issue #12)
4 is a good idea, ==> new issue #13
